#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyarrow==21.0.0"]
# ///
"""Build a reproducible long-context holdout from pinned software repositories.

The repositories are selected from the permissive-license portion of
SWE-bench Science, but this builder does not copy task instructions, verifier
material, trajectories, or answer patches.  It emits only public files from
the repositories at their recorded base commits.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

WORD_RE = re.compile(r"\w+", re.UNICODE)
SOURCE_INDEX_REPOSITORY = "OpenMOSS-Team/SWE-bench-Science"
SOURCE_INDEX_REVISION = "7e7084280fdf5d21811ff04c7acb0b738984c705"
SOURCE_INDEX_PATH = "data/tasks.csv"
ALLOWED_SUFFIXES = {
    ".c",
    ".cc",
    ".cmake",
    ".cpp",
    ".cu",
    ".cuh",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".java",
    ".js",
    ".json",
    ".kt",
    ".md",
    ".py",
    ".pyi",
    ".pyx",
    ".pxd",
    ".rs",
    ".rst",
    ".sh",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".yaml",
    ".yml",
}
ALLOWED_FILENAMES = {
    "CMakeLists.txt",
    "Dockerfile",
    "LICENSE",
    "LICENSE.txt",
    "Makefile",
    "NOTICE",
    "README",
}
EXCLUDED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "eigen",
    "external",
    "extern",
    "fixtures",
    "generated",
    "node_modules",
    "site-packages",
    "third_party",
    "thirdparty",
    "vendor",
}
GENERATED_MARKERS = (
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "do not edit this file",
    "generated by",
)


@dataclass(frozen=True)
class Repository:
    slug: str
    url: str
    commit: str
    license_spdx: str
    task_id: str


# All selected source repositories are Apache-2.0, which keeps redistribution
# terms uniform while still spanning numerical computing, ML, optimization,
# tensor networks, and labeled-array infrastructure.
REPOSITORIES = (
    Repository(
        slug="diffrax",
        url="https://github.com/patrick-kidger/diffrax",
        commit="56d78e1acbdc9c1493caef17a34777931430f3bf",
        license_spdx="Apache-2.0",
        task_id="034",
    ),
    Repository(
        slug="xarray",
        url="https://github.com/pydata/xarray",
        commit="0b071e369a88f6672accc2a99c40d3b4b334f2f9",
        license_spdx="Apache-2.0",
        task_id="088",
    ),
    Repository(
        slug="cvxpy",
        url="https://github.com/cvxpy/cvxpy",
        commit="5f57b6408864caab207c28f773a14c6261689abe",
        license_spdx="Apache-2.0",
        task_id="076",
    ),
    Repository(
        slug="monai",
        url="https://github.com/Project-MONAI/MONAI",
        commit="18daff1d8b26002b02de526cc19b92a9a4907f89",
        license_spdx="Apache-2.0",
        task_id="053",
    ),
    Repository(
        slug="pyscf",
        url="https://github.com/pyscf/pyscf",
        commit="802cd37e9dc6abb52f30d84bb422b6ee15493fc9",
        license_spdx="Apache-2.0",
        task_id="033",
    ),
    Repository(
        slug="quimb",
        url="https://github.com/jcmgray/quimb",
        commit="79594e405ac72da908cdd7a1058911afc256c483",
        license_spdx="Apache-2.0",
        task_id="050",
    ),
)


def run(*command: str, cwd: Path | None = None) -> str:
    return subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=True,
    ).stdout.strip()


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalized_words(text: str) -> list[str]:
    return WORD_RE.findall(text.casefold())


def shingle_hashes(text: str, width: int) -> set[int]:
    words = normalized_words(text)
    if len(words) < width:
        return set()
    return {
        int.from_bytes(
            hashlib.blake2b(
                "\0".join(words[index : index + width]).encode(), digest_size=8
            ).digest(),
            "big",
        )
        for index in range(len(words) - width + 1)
    }


def prepare_repository(spec: Repository, workspace: Path) -> tuple[Path, str]:
    destination = workspace / spec.slug
    if not destination.exists():
        destination.mkdir(parents=True)
        run("git", "init", "--quiet", str(destination))
        run("git", "remote", "add", "origin", spec.url, cwd=destination)
    if not (destination / ".git").is_dir():
        raise SystemExit(f"existing path is not a Git repository: {destination}")
    origin = run("git", "remote", "get-url", "origin", cwd=destination)
    if origin.rstrip("/") != spec.url.rstrip("/"):
        raise SystemExit(f"origin mismatch for {spec.slug}: expected {spec.url}, found {origin}")
    try:
        run("git", "cat-file", "-e", f"{spec.commit}^{{commit}}", cwd=destination)
    except subprocess.CalledProcessError:
        run(
            "git",
            "fetch",
            "--quiet",
            "--depth=1",
            "origin",
            spec.commit,
            cwd=destination,
        )
    resolved = run("git", "rev-parse", spec.commit, cwd=destination)
    if resolved != spec.commit:
        raise SystemExit(
            f"commit mismatch for {spec.slug}: expected {spec.commit}, found {resolved}"
        )
    tree = run("git", "rev-parse", f"{spec.commit}^{{tree}}", cwd=destination)
    return destination, tree


def eligible_path(path: str) -> bool:
    parsed = PurePosixPath(path)
    if any(part.casefold() in EXCLUDED_PARTS for part in parsed.parts):
        return False
    return parsed.name in ALLOWED_FILENAMES or parsed.suffix.casefold() in ALLOWED_SUFFIXES


def category_for_path(path: str) -> str:
    parsed = PurePosixPath(path)
    parts = {part.casefold() for part in parsed.parts}
    if parts & {"test", "tests", "testing"} or parsed.name.casefold().startswith("test_"):
        return "tests"
    if parts & {"doc", "docs", "documentation", "example", "examples"}:
        return "docs"
    if parsed.suffix.casefold() in {".md", ".rst"} or parsed.name.startswith("README"):
        return "docs"
    return "source"


def read_git_file(repository: Path, commit: str, path: str) -> bytes:
    return subprocess.run(
        ["git", "show", f"{commit}:{path}"],
        cwd=repository,
        check=True,
        capture_output=True,
    ).stdout


def repository_license(repository: Path, commit: str) -> tuple[str, bytes]:
    paths = run("git", "ls-tree", "-r", "--name-only", commit, cwd=repository)
    candidates = [
        path
        for path in paths.splitlines()
        if len(PurePosixPath(path).parts) == 1
        and PurePosixPath(path).name.casefold().startswith(("license", "copying"))
    ]
    if not candidates:
        raise SystemExit(f"no root license file found at {repository}@{commit}")
    path = min(candidates)
    return path, read_git_file(repository, commit, path)


def candidate_files(
    spec: Repository,
    repository: Path,
    calibration_shingles: set[int],
    seed: str,
    maximum_file_bytes: int,
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    paths = run("git", "ls-tree", "-r", "--name-only", spec.commit, cwd=repository)
    rows: list[dict[str, Any]] = []
    rejected = {
        "path": 0,
        "size": 0,
        "binary_or_encoding": 0,
        "generated": 0,
        "calibration_overlap": 0,
    }
    for path in paths.splitlines():
        if not eligible_path(path):
            rejected["path"] += 1
            continue
        payload = read_git_file(repository, spec.commit, path)
        if not 200 <= len(payload) <= maximum_file_bytes:
            rejected["size"] += 1
            continue
        if b"\0" in payload:
            rejected["binary_or_encoding"] += 1
            continue
        try:
            content = payload.decode("utf-8")
        except UnicodeDecodeError:
            rejected["binary_or_encoding"] += 1
            continue
        if any(marker in content[:1000].casefold() for marker in GENERATED_MARKERS):
            rejected["generated"] += 1
            continue
        overlap = len(shingle_hashes(content, 20) & calibration_shingles)
        if overlap:
            rejected["calibration_overlap"] += 1
            continue
        selection_key = sha256_bytes(f"{seed}\0{spec.slug}\0{path}".encode())
        rows.append(
            {
                "repository": spec.slug,
                "repository_url": spec.url,
                "commit": spec.commit,
                "license_spdx": spec.license_spdx,
                "source_index_task_id": spec.task_id,
                "path": path,
                "category": category_for_path(path),
                "selection_key": selection_key,
                "content": content,
                "content_bytes": len(payload),
                "content_chars": len(content),
                "content_sha256": sha256_bytes(payload),
                "shared_calibration_20_word_shingles": overlap,
            }
        )
    return rows, rejected


def select_files(candidates: list[dict[str, Any]], target_chars: int) -> list[dict[str, Any]]:
    quotas = {
        "source": int(target_chars * 0.55),
        "tests": int(target_chars * 0.25),
        "docs": int(target_chars * 0.20),
    }
    selected: list[dict[str, Any]] = []
    selected_paths: set[str] = set()
    for category, quota in quotas.items():
        total = 0
        rows = sorted(
            (row for row in candidates if row["category"] == category),
            key=lambda row: (row["selection_key"], row["path"]),
        )
        for row in rows:
            selected.append(row)
            selected_paths.add(str(row["path"]))
            total += int(row["content_chars"])
            if total >= quota:
                break
    total = sum(int(row["content_chars"]) for row in selected)
    if total < target_chars:
        remaining = sorted(
            (row for row in candidates if row["path"] not in selected_paths),
            key=lambda row: (row["selection_key"], row["path"]),
        )
        for row in remaining:
            selected.append(row)
            total += int(row["content_chars"])
            if total >= target_chars:
                break
    return sorted(selected, key=lambda row: str(row["path"]))


def render_repository(spec: Repository, tree: str, selected: list[dict[str, Any]]) -> str:
    paths = "\n".join(str(row["path"]) for row in selected)
    blocks = [
        (
            f'<repository name="{spec.slug}" url="{spec.url}" '
            f'commit="{spec.commit}" tree="{tree}" license="{spec.license_spdx}">\n'
            f"<selected-file-tree>\n{paths}\n</selected-file-tree>"
        )
    ]
    for row in selected:
        blocks.append(
            f'<file path="{row["path"]}" category="{row["category"]}" '
            f'sha256="{row["content_sha256"]}">\n{row["content"]}\n</file>'
        )
    blocks.append("</repository>")
    return "\n\n".join(blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--calibration-text", type=Path, required=True)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--target-chars-per-repository", type=int, default=1_250_000)
    parser.add_argument("--minimum-chars-per-repository", type=int, default=350_000)
    parser.add_argument("--minimum-combined-chars", type=int, default=5_000_000)
    parser.add_argument("--maximum-file-bytes", type=int, default=262_144)
    parser.add_argument("--seed", default="agentic-coding-long-context-v1")
    parser.add_argument("--verified-token-count", type=int)
    parser.add_argument("--tokenizer")
    parser.add_argument("--tokenizer-revision")
    args = parser.parse_args()
    tokenization_values = (
        args.verified_token_count,
        args.tokenizer,
        args.tokenizer_revision,
    )
    if any(value is not None for value in tokenization_values) and not all(
        value is not None for value in tokenization_values
    ):
        raise SystemExit(
            "verified token count, tokenizer, and tokenizer revision must be supplied together"
        )

    calibration_text = args.calibration_text.read_text(encoding="utf-8")
    calibration_shingles = shingle_hashes(calibration_text, 20)
    args.workspace.mkdir(parents=True, exist_ok=True)
    repository_output = args.output_dir / "repositories"
    repository_output.mkdir(parents=True, exist_ok=True)
    license_output = args.output_dir / "licenses"
    license_output.mkdir(parents=True, exist_ok=True)

    manifest_rows: list[dict[str, Any]] = []
    repository_receipts = []
    rendered_streams = []
    for spec in REPOSITORIES:
        repository, tree = prepare_repository(spec, args.workspace)
        license_path, license_payload = repository_license(repository, spec.commit)
        license_artifact = license_output / f"{spec.slug}-{PurePosixPath(license_path).name}"
        license_artifact.write_bytes(license_payload)
        candidates, rejected = candidate_files(
            spec,
            repository,
            calibration_shingles,
            args.seed,
            args.maximum_file_bytes,
        )
        selected = select_files(candidates, args.target_chars_per_repository)
        selected_chars = sum(int(row["content_chars"]) for row in selected)
        if selected_chars < args.minimum_chars_per_repository:
            raise SystemExit(
                f"{spec.slug} produced only {selected_chars:,} of "
                f"{args.minimum_chars_per_repository:,} minimum characters"
            )
        stream = render_repository(spec, tree, selected)
        output_path = repository_output / f"{spec.slug}.txt"
        output_path.write_text(stream, encoding="utf-8")
        rendered_streams.append(stream)
        for ordinal, row in enumerate(selected):
            manifest_rows.append(
                {
                    **row,
                    "repository_tree": tree,
                    "ordinal_within_repository": ordinal,
                }
            )
        repository_receipts.append(
            {
                "slug": spec.slug,
                "url": spec.url,
                "commit": spec.commit,
                "tree": tree,
                "license_spdx": spec.license_spdx,
                "source_index_task_id": spec.task_id,
                "license_artifact": {
                    "source_path": license_path,
                    "path": str(license_artifact),
                    "bytes": license_artifact.stat().st_size,
                    "sha256": sha256_file(license_artifact),
                },
                "candidate_files": len(candidates),
                "selected_files": len(selected),
                "selected_content_chars": selected_chars,
                "selected_by_category": {
                    category: sum(row["category"] == category for row in selected)
                    for category in ("source", "tests", "docs")
                },
                "selected_characters_by_category": {
                    category: sum(
                        int(row["content_chars"]) for row in selected if row["category"] == category
                    )
                    for category in ("source", "tests", "docs")
                },
                "rejected": rejected,
                "artifact": {
                    "path": str(output_path),
                    "bytes": output_path.stat().st_size,
                    "sha256": sha256_file(output_path),
                },
            }
        )
        print(
            f"{spec.slug}: selected {len(selected):,} files and "
            f"{selected_chars:,} content characters"
        )

    combined_path = args.output_dir / "agentic-coding-long-context.txt"
    combined_path.write_text("\n".join(rendered_streams), encoding="utf-8")
    if combined_path.stat().st_size < args.minimum_combined_chars:
        raise SystemExit(
            f"combined stream is only {combined_path.stat().st_size:,} bytes; "
            f"minimum is {args.minimum_combined_chars:,}"
        )
    combined_shingles = shingle_hashes(combined_path.read_text(encoding="utf-8"), 20)
    combined_overlap = len(combined_shingles & calibration_shingles)
    if combined_overlap:
        raise SystemExit(f"combined stream has {combined_overlap:,} shared calibration shingles")
    manifest_path = args.output_dir / "agentic-coding-files.parquet"
    pq.write_table(pa.Table.from_pylist(manifest_rows), manifest_path, compression="zstd")
    receipt_path = args.output_dir / "agentic-coding-receipt.json"
    receipt: dict[str, Any] = {
        "schema_version": 1,
        "purpose": "evaluation-only agentic-coding long-context holdout; never calibration input",
        "construction": {
            "representation": "selected file tree followed by complete public file contents",
            "seed": args.seed,
            "target_chars_per_repository": args.target_chars_per_repository,
            "minimum_chars_per_repository": args.minimum_chars_per_repository,
            "minimum_combined_chars": args.minimum_combined_chars,
            "maximum_file_bytes": args.maximum_file_bytes,
            "category_character_targets": {
                "source": 0.55,
                "tests": 0.25,
                "docs": 0.20,
            },
            "task_prompts_included": False,
            "verifier_material_included": False,
            "trajectories_included": False,
        },
        "source_index": {
            "repository": SOURCE_INDEX_REPOSITORY,
            "revision": SOURCE_INDEX_REVISION,
            "path": SOURCE_INDEX_PATH,
            "role": "repository, commit, and source-license selection only",
        },
        "repositories": repository_receipts,
        "calibration_exclusion": {
            "path": str(args.calibration_text),
            "sha256": sha256_file(args.calibration_text),
            "twenty_word_shingles": len(calibration_shingles),
            "maximum_shared_shingles_per_selected_file": 0,
            "combined_stream_twenty_word_shingles": len(combined_shingles),
            "combined_stream_shared_twenty_word_shingles": combined_overlap,
        },
        "artifacts": {
            "combined_text": {
                "path": str(combined_path),
                "bytes": combined_path.stat().st_size,
                "sha256": sha256_file(combined_path),
            },
            "file_manifest": {
                "path": str(manifest_path),
                "bytes": manifest_path.stat().st_size,
                "sha256": sha256_file(manifest_path),
                "contains_source_text": True,
            },
        },
    }
    if args.verified_token_count is not None:
        receipt["tokenization"] = {
            "tokenizer": args.tokenizer,
            "tokenizer_revision": args.tokenizer_revision,
            "tokens_without_bos": args.verified_token_count,
        }
    receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
